-- Stock Oracle — Supabase Tables
-- Paste this into Supabase SQL Editor (supabase.com → SQL Editor → New Query)

-- 1. Claude AI Predictions (learning from wins/losses)
CREATE TABLE predictions (
  id bigint generated by default as identity primary key,
  symbol text not null,
  action text not null,           -- BUY, SKIP
  confidence int,                 -- 1-10
  thesis text,
  risk_level text,                -- LOW, MEDIUM, HIGH
  target_pct numeric,
  stop_pct numeric,
  timeframe_days int,
  entry_price numeric,
  gem_score int,
  consensus text,
  provider text default 'claude', -- claude or gemini
  outcome text,                   -- win, loss, null (open)
  exit_price numeric,
  actual_pct numeric,
  exit_reason text,
  settled_at timestamptz,
  created_at timestamptz default now()
);

-- 2. Polymarket Bets (simulation)
CREATE TABLE poly_bets (
  id bigint generated by default as identity primary key,
  market_id text,
  question text,
  outcome text,                   -- Yes, No
  shares numeric,
  entry_price numeric,
  amount numeric,
  confidence int,
  thesis text,
  strategy text,                  -- edge, arb, safe, whale, etc.
  edge_pct numeric,
  status text default 'open',     -- open, won, lost
  settlement_price numeric,
  pnl numeric,
  settled_at timestamptz,
  created_at timestamptz default now()
);

-- 3. Stock Trades (Alpaca auto-trades)
CREATE TABLE trades (
  id bigint generated by default as identity primary key,
  symbol text not null,
  side text default 'buy',
  qty numeric,
  entry_price numeric,
  amount numeric,
  consensus text,
  gem_score int,
  claude_confidence int,
  claude_thesis text,
  signals text[],
  exit_price numeric,
  pnl numeric,
  exit_reason text,
  closed_at timestamptz,
  created_at timestamptz default now()
);

-- Enable Row Level Security (required by Supabase)
ALTER TABLE predictions ENABLE ROW LEVEL SECURITY;
ALTER TABLE poly_bets ENABLE ROW LEVEL SECURITY;
ALTER TABLE trades ENABLE ROW LEVEL SECURITY;

-- Allow anon key to read/write (since this is a private backend)
CREATE POLICY "Allow all on predictions" ON predictions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on poly_bets" ON poly_bets FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on trades" ON trades FOR ALL USING (true) WITH CHECK (true);

-- Indexes for fast lookups
CREATE INDEX idx_predictions_symbol ON predictions(symbol);
CREATE INDEX idx_predictions_outcome ON predictions(outcome);
CREATE INDEX idx_poly_bets_status ON poly_bets(status);
CREATE INDEX idx_trades_symbol ON trades(symbol);
CREATE INDEX idx_trades_closed ON trades(closed_at);
